# Generated by Django 3.1.3 on 2024-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='useremail',
            field=models.EmailField(max_length=128, verbose_name='useremail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username'),
        ),
    ]
