# Generated by Django 3.1.3 on 2024-04-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_auto_20240412_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='useremail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=8, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=8, null=True, verbose_name='닉네임'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.CharField(default=1, max_length=17, unique=True, verbose_name='아이디'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, verbose_name='비밀번호'),
        ),
    ]
