# Generated by Django 3.1.3 on 2024-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240413_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=128, null=True, verbose_name='닉네임'),
        ),
    ]
