# Generated by Django 3.1.3 on 2024-04-13 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBoardPost',
            fields=[
                ('title', models.CharField(max_length=20, null=True)),
                ('content', models.TextField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.noticeboardpost')),
            ],
        ),
    ]
